import { GeistSans } from 'geist/font/sans';
import './globals.css';
import 'react-responsive-modal/styles.css';

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
   return (
      <html lang='en'>
         <body className={`${GeistSans.className} antialiased bg-gray-200`}>
            {children}
         </body>
      </html>
   );
}
